[workspace]
members = [
    "text_retrieval",
    "calculator",
    "upload_logs",
    "guess_num"
]
resolver = "2"

[profile.release]
lto = true # 优化等级
panic = "abort" # panic 时的行为
codegen-units = 1 # 编译单元数量
